export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const GET_PARENT_CATEGORIES='GET_PARENT_CATEGORIES';
export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';
export const SIGN_UP_CUSTOMER='SIGN_UP_CUSTOMER';
export const SIGN_UP_SELLER='SIGN_UP_SELLER';
export const SIGN_UP_CUSTOMER_SUCCESS='SIGN_UP_CUSTOMER_SUCCESS';
export const SIGN_UP_SELLER_SUCCESS='SIGN_UP_SELLER_SUCCESS';
export const USER_ACTIVATE_SUCCESS='USER_ACTIVATE_SUCCESS';
export const RESEND_ACTIVATION_LINK_SUCCESS='RESEND_ACTIVATION_LINK_SUCCESS';
export const FORGOT_PASSWORD_LINK_SUCCESS='FORGOT_PASSWORD_LINK_SUCCESS';
export const FORGOT_PASSWORD_RESET_SUCCESS='FORGOT_PASSWORD_RESET_SUCCESS';

export const ADMIN_START='ADMIN_START';
export const ADMIN_FAIL='ADMIN_FAIL';
export const ADMIN_LIST_CUSTOMER_SUCCESS='ADMIN_LIST_CUSTOMER_SUCCESS';
export const ADMIN_LIST_SELLER_SUCCESS='ADMIN_LIST_SELLER_SUCCESS';
export const ACTIVATE_DEACTIVATE_CUSTOMER_SUCCESS='ACTIVATE_DEACTIVATE_CUSTOMER_SUCCESS';

export const CUSTOMER_START='CUSTOMER_START';
export const CUSTOMER_FAIL='CUSTOMER_FAIL';
export const CUSTOMER_PROFILE_SUCCESS='CUSTOMER_PROFILE_SUCCESS';
export const CUSTOMER_ADDRESSES_SUCCESS='CUSTOMER_ADDRESSES_SUCCESS';
export const ADD_ADDRESS_SUCCESS='ADD_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_SUCCESS='DELETE_ADDRESS_SUCCESS';
export const UPDATE_PASSWORD_SUCCESS='UPDATE_PASSWORD_SUCCESS';
export const UPDATE_ADDRESS_SUCCESS='UPDATE_ADDRESS_SUCCESS';
export const UPDATE_CUSTOMER_PROFILE_SUCCESS='UPDATE_CUSTOMER_PROFILE_SUCCESS';

export const SELLER_START='SELLER_START';
export const SELLER_FAIL='SELLER_FAIL';
export const SELLER_PROFILE_SUCCESS='SELLER_PROFILE_SUCCESS';
export const SELLER_ADDRESS_SUCCESS='SELLER_ADDRESS_SUCCESS';
export const UPDATE_SELLER_PROFILE_SUCCESS='UPDATE_CUSTOMER_PROFILE_SUCCESS';
export const IMAGE_UPLOAD_SUCCESS='IMAGE_UPLOAD_SUCCESS';

export const CATEGORY_START='CATEGORY_START';
export const CATEGORY_FAIL='CATEGORY_FAIL';
export const CATEGORY_ADD_METADATA_FIELD_SUCCESS='CATEGORY_ADD_METADATA_FIELD_SUCCESS';
export const CATEGORY_VIEW_ALL_METADATA_FIELDS_SUCCESS='CATEGORY_VIEW_ALL_METADATA_FIELDS_SUCCESS';
export const ADD_CATEGORY_SUCCESS='ADD_CATEGORY_SUCCESS';

export const VIEW_CATEGORY_SUCCESS='VIEW_CATEGORY_SUCCESS';
export const VIEW_ALL_CATEGORIES_SUCCESS='VIEW_ALL_CATEGORIES_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS='UPDATE_CATEGORY_SUCCESS';

export const PRODUCT_START='PRODUCT_START';
export const PRODUCT_FAIL='PRODUCT_FAIL';
export const VIEW_ALL_PRODUCTS_SUCCESS='VIEW_ALL_PRODUCTS_SUCCESS';
export const VIEW_ALL_PRODUCTS_VARIATION='VIEW_ALL_PRODUCTS_VARIATION';
export const VIEW_PRODUCT_DETAILS_SUCCESS='VIEW_PRODUCT_DETAILS_SUCCESS';
export const VIEW_PRODUCT_SUCCESS='VIEW_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_SUCCESS='SEARCH_PRODUCT_SUCCESS';

export const ACTIVATE_DEACTIVATE_PRODUCT_SUCCESS='ACTIVATE_DEACTIVATE_PRODUCT_SUCCESS';
export const ADMIN_VIEW_ALL_PRODUCTS='ADMIN_VIEW_ALL_PRODUCTS';
export const ADMIN_VIEW_PRODUCT_DETAILS_SUCCESS='ADMIN_VIEW_PRODUCT_DETAILS_SUCCESS';
export const AUTH_PRODUCTS_SUCCESS='AUTH_PRODUCTS_SUCCESS';
export const ADD_PRODUCT_SUCCESS=' ADD_PRODUCT_SUCCESS';
export const VIEW_ALL_PRODUCTS_SELLER_SUCCESS='VIEW_ALL_PRODUCTS_SELLER_SUCCESS';
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS';
export const VIEW_PRODUCT_VARIATIONS_SUCCESS='VIEW_PRODUCT_VARIATIONS_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS='UPDATE_PRODUCT_SUCCESS';
export const ADD_PRODUCT_VARIATION_SUCCESS='ADD_PRODUCT_VARIATION_SUCCESS';
export const UPDATE_PRODUCT_VARIATION_SUCCESS='UPDATE_PRODUCT_VARIATION_SUCCESS';
export const ADD_TO_CART_SUCCESS='ADD_TO_CART_SUCCESS';
export const AUTH_FETCH_ORDERS_SUCCESS='AUTH_FETCH_ORDERS_SUCCESS';
export const DELETE_ORDER_SUCCESS='DELETE_ORDER_SUCCESS';











